/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UrunRouteImport } from './routes/urun'
import { Route as IletisimRouteImport } from './routes/iletisim'
import { Route as FiyatlandirmaRouteImport } from './routes/fiyatlandirma'
import { Route as DokumanlarRouteImport } from './routes/dokumanlar'
import { Route as IndexRouteImport } from './routes/index'

const UrunRoute = UrunRouteImport.update({
  id: '/urun',
  path: '/urun',
  getParentRoute: () => rootRouteImport,
} as any)
const IletisimRoute = IletisimRouteImport.update({
  id: '/iletisim',
  path: '/iletisim',
  getParentRoute: () => rootRouteImport,
} as any)
const FiyatlandirmaRoute = FiyatlandirmaRouteImport.update({
  id: '/fiyatlandirma',
  path: '/fiyatlandirma',
  getParentRoute: () => rootRouteImport,
} as any)
const DokumanlarRoute = DokumanlarRouteImport.update({
  id: '/dokumanlar',
  path: '/dokumanlar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dokumanlar': typeof DokumanlarRoute
  '/fiyatlandirma': typeof FiyatlandirmaRoute
  '/iletisim': typeof IletisimRoute
  '/urun': typeof UrunRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dokumanlar': typeof DokumanlarRoute
  '/fiyatlandirma': typeof FiyatlandirmaRoute
  '/iletisim': typeof IletisimRoute
  '/urun': typeof UrunRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dokumanlar': typeof DokumanlarRoute
  '/fiyatlandirma': typeof FiyatlandirmaRoute
  '/iletisim': typeof IletisimRoute
  '/urun': typeof UrunRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dokumanlar' | '/fiyatlandirma' | '/iletisim' | '/urun'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dokumanlar' | '/fiyatlandirma' | '/iletisim' | '/urun'
  id:
    | '__root__'
    | '/'
    | '/dokumanlar'
    | '/fiyatlandirma'
    | '/iletisim'
    | '/urun'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DokumanlarRoute: typeof DokumanlarRoute
  FiyatlandirmaRoute: typeof FiyatlandirmaRoute
  IletisimRoute: typeof IletisimRoute
  UrunRoute: typeof UrunRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/urun': {
      id: '/urun'
      path: '/urun'
      fullPath: '/urun'
      preLoaderRoute: typeof UrunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iletisim': {
      id: '/iletisim'
      path: '/iletisim'
      fullPath: '/iletisim'
      preLoaderRoute: typeof IletisimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fiyatlandirma': {
      id: '/fiyatlandirma'
      path: '/fiyatlandirma'
      fullPath: '/fiyatlandirma'
      preLoaderRoute: typeof FiyatlandirmaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dokumanlar': {
      id: '/dokumanlar'
      path: '/dokumanlar'
      fullPath: '/dokumanlar'
      preLoaderRoute: typeof DokumanlarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DokumanlarRoute: DokumanlarRoute,
  FiyatlandirmaRoute: FiyatlandirmaRoute,
  IletisimRoute: IletisimRoute,
  UrunRoute: UrunRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
